import http from 'node:http';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {mkdir,rm,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {lookup} from 'node:dns/promises';
import net from 'node:net';
import path from 'node:path';

const PORT=Number(process.env.PORT||3000), ROOT='/tmp/jstowav', TTL=600000;
await mkdir(ROOT,{recursive:true});
const jobs=new Map();
setInterval(async()=>{const now=Date.now();for(const [k,j] of jobs)if(j.expires<=now){jobs.delete(k);await rm(j.dir,{recursive:true,force:true});}},30000).unref();
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj));}
function privateIP(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168;}return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');}
async function safeUrl(raw){let u;try{u=new URL(raw)}catch{throw Error('올바른 URL이 아닙니다.')}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('http/https URL만 허용됩니다.');const addrs=await lookup(u.hostname,{all:true});if(!addrs.length||addrs.some(x=>privateIP(x.address)))throw Error('내부 네트워크 주소는 허용되지 않습니다.');return u;}
function extractM3u8(text){const decoded=String(text).replaceAll('\\/','/');const re=/https?:\/\/[^\s"'<>]+?\.m3u8(?:\?[^\s"'<>]*)?/ig;const m=decoded.match(re);return m?.[0]||null;}
async function fetchText(url){const u=await safeUrl(url);const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'user-agent':'jstowav/1.1'}});if(r.status>=300&&r.status<400&&r.headers.get('location'))return fetchText(new URL(r.headers.get('location'),u).href);if(!r.ok)throw Error(`원격 서버 HTTP ${r.status}`);const b=await r.arrayBuffer();if(b.byteLength>2_000_000)throw Error('페이지/플레이리스트가 너무 큽니다.');return {text:new TextDecoder().decode(b),url:r.url||u.href};}
async function discover(raw){const pasted=extractM3u8(raw);if(pasted)return (await safeUrl(pasted)).href;const u=await safeUrl(raw.trim());if(u.pathname.toLowerCase().endsWith('.m3u8'))return u.href;const {text,url}=await fetchText(u.href);const found=extractM3u8(text);if(found)return (await safeUrl(new URL(found,url).href)).href;const rel=[...text.matchAll(/["']([^"']+\.m3u8(?:\?[^"']*)?)["']/ig)];for(const m of rel){try{return (await safeUrl(new URL(m[1],url).href)).href}catch{}}throw Error('페이지/텍스트에서 m3u8 링크를 찾지 못했습니다.');}
function run(cmd,args,timeout=180000){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','ignore','pipe']});let e='';const t=setTimeout(()=>{p.kill('SIGKILL');reject(Error('변환 시간 제한을 초과했습니다.'));},timeout);p.stderr.on('data',d=>{if(e.length<8000)e+=d});p.on('error',reject);p.on('close',c=>{clearTimeout(t);c===0?resolve():reject(Error('변환 실패: '+e.slice(-600)));});});}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>100000)throw Error('요청이 너무 큽니다.');}return JSON.parse(s||'{}');}
const page=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>JS to WAV</title><style>body{font-family:system-ui;background:#0b1020;color:#eef2ff;margin:0}.w{max-width:760px;margin:8vh auto;padding:28px}.card{background:#151b31;padding:28px;border-radius:20px;box-shadow:0 20px 60px #0006}h1{margin-top:0}textarea,button{box-sizing:border-box;width:100%;padding:15px;border-radius:12px;border:1px solid #39415e;font-size:15px}textarea{min-height:220px;resize:vertical;background:#0e1428;color:white;font-family:ui-monospace,monospace}button{margin-top:12px;background:#eef2ff;color:#111827;font-weight:700;cursor:pointer}.muted{color:#aab3cf;font-size:14px}.out{margin-top:18px;white-space:pre-wrap}a{color:#9fc1ff}</style><div class="w"><div class="card"><h1>JS to WAV</h1><p>페이지 URL, m3u8 URL 또는 Network/Response 로그 전체를 그대로 붙여넣으세요.</p><textarea id="u" placeholder="GET https://…/2000k.m3u8 200\n\nResponse Headers\n…\n#EXTM3U\n…"></textarea><button id="b">m3u8 찾아 WAV 만들기</button><div class="out" id="o"></div><p class="muted">본인이 이용 권한이 있는 미디어에만 사용하세요. DRM/접근통제 우회는 지원하지 않습니다. 생성 파일은 10분 후 삭제됩니다.</p></div></div><script>b.onclick=async()=>{b.disabled=true;o.textContent='m3u8 탐색 및 변환 중…';try{let r=await fetch('/api/convert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:u.value})});let j=await r.json();if(!r.ok)throw Error(j.error);o.innerHTML='완료 · '+j.sizeMB+' MB · <a href="'+j.download+'">WAV 다운로드</a><br>링크는 10분 동안 유효합니다.'}catch(e){o.textContent='오류: '+e.message}finally{b.disabled=false}}</script></html>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(page)}if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{status:'ok'});if(req.method==='POST'&&u.pathname==='/api/convert'){const b=await body(req),input=b.input??b.url;if(typeof input!=='string'||!input.trim())throw Error('URL 또는 로그 텍스트를 입력하세요.');const m3u8=await discover(input);const mu=await safeUrl(m3u8);const id=randomUUID(),dir=path.join(ROOT,id),file=path.join(dir,'audio.wav');await mkdir(dir,{mode:0o700});try{await run('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-protocol_whitelist','file,http,https,tcp,tls,crypto','-i',mu.href,'-vn','-acodec','pcm_s16le','-ar','44100','-ac','2','-y',file]);const st=await stat(file);if(st.size>500_000_000)throw Error('생성 파일이 너무 큽니다.');jobs.set(id,{dir,file,expires:Date.now()+TTL});return json(res,200,{download:'/download/'+id,sizeMB:(st.size/1048576).toFixed(1),expiresIn:600});}catch(e){await rm(dir,{recursive:true,force:true});throw e;}}if(req.method==='GET'&&u.pathname.startsWith('/download/')){const id=u.pathname.slice(10),j=jobs.get(id);if(!j||j.expires<=Date.now())return json(res,404,{error:'링크가 만료되었거나 존재하지 않습니다.'});const st=await stat(j.file);res.writeHead(200,{'content-type':'audio/wav','content-length':st.size,'content-disposition':'attachment; filename="audio.wav"','cache-control':'private, no-store'});return createReadStream(j.file).pipe(res)}json(res,404,{error:'not found'});}catch(e){json(res,400,{error:String(e.message||e).replace(/[\r\n]+/g,' ')})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`jstowav listening ${PORT}`));
